# Generated by Django 2.1.5 on 2020-03-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
