# Generated by Django 3.0.4 on 2020-03-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_node_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='service',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
