# Generated by Django 3.0.4 on 2020-03-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200321_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.TextField(null=True),
        ),
    ]
