# Generated by Django 3.0.3 on 2020-03-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_author_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='extAuthor',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='ext_friends',
            field=models.ManyToManyField(related_name='ext_followers', to='users.extAuthor'),
        ),
    ]
