# Generated by Django 3.0.3 on 2020-03-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200325_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='ext_friends',
            new_name='ext_following',
        ),
        migrations.AddField(
            model_name='author',
            name='ext_follower',
            field=models.ManyToManyField(related_name='ext_followings', to='users.extAuthor'),
        ),
    ]
