# Generated by Django 3.0.4 on 2020-04-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200326_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='authentication',
            field=models.TextField(null=True),
        ),
    ]
