# Generated by Django 3.0.2 on 2020-03-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.IntegerField(default=4),
        ),
    ]
