# Generated by Django 3.0.2 on 2020-03-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='markdown',
        ),
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(default='text/plain', max_length=150),
            preserve_default=False,
        ),
    ]
