# Generated by Django 3.0.2 on 2020-03-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200307_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gh_event_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
